spring.application.name=demo
server.port=10000
spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.db=${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
geoserver.url=http://geoserver:8080/geoserver
geoserver.username=${GEOSERVER_ADMIN_USER}
geoserver.password=${GEOSERVER_ADMIN_PASSWORD}
# Pobiera Base64 service account ze zmiennej środowiskowej.
firebase.service-account-json-base64=${FIREBASE_SERVICE_ACCOUNT_JSON_BASE64:}
app.base-url=http://localhost:10001
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
