name: Build, push and deploy Docker image to Docker
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: self-hosted

    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file 
        run: |
          echo "ENV_NAME=${{github.ref_name}}" >> .env
          echo "POSTGRES_PORT=${{secrets.POSTGRES_PORT}}" >> .env
          echo "POSTGRES_USER=${{secrets.POSTGRES_USER}}" >> .env
          echo "POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}" >> .env
          echo "POSTGRES_DB=${{secrets.POSTGRES_DB}}" >> .env
          echo "SPRINGBOOT_PORT=${{secrets.SPRINGBOOT_PORT}}" >> .env
          echo "GEOSERVER_PORT=${{secrets.GEOSERVER_PORT}}" >> .env
          echo "NGINX_PORT=${{secrets.NGINX_PORT}}" >> .env
          echo "GEOSERVER_ADMIN_PASSWORD=${{secrets.GEOSERVER_ADMIN_PASSWORD}}" >> .env
          echo "GEOSERVER_ADMIN_USER=${{secrets.GEOSERVER_ADMIN_USER}}" >> .env


      - name: Launch Docker Environment
        env: 
          ENV_NAME: ${{github.ref_name}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          SPRINGBOOT_PORT: ${{secrets.SPRINGBOOT_PORT}}
          GEOSERVER_PORT: ${{secrets.GEOSERVER_PORT}}
          NGINX_PORT: ${{secrets.NGINX_PORT}}
          GEOSERVER_ADMIN_PASSWORD: ${{secrets.GEOSERVER_PASSWORD}}
          GEOSERVER_ADMIN_USER: ${{secrets.GEOSERVER_ADMIN_USER}}
        run: |
          docker-compose -f docker-compose/docker-compose.yml -p angularspringbootapp up --build -d